### PR TITLE
Update styles at Cheatsheet // improve code font

### PR DESCRIPTION
**Pull request by diepoe**
This should bring the design from #153 back to the cheatsheet. This PR also updates the font thats used for the code highlighting to `FiraCode`. I hope this font change is ok to you, otherwise I would be happy about your feedback.

## preview
Screenshot_2021-02-10 Cheatsheet - Svelte Society

### CODE REVIEW

**Comment by kevmodrome** [comment]
This looks good! We might need to add the font to the assets folder as well.

**Comment by diepoe** [comment]
> This looks good! We might need to add the font to the assets folder as well.

I think I added it [here](https://github.com/svelte-society/sveltesociety.dev/pull/173/files#diff-88b4d6b36a971884abd7a587f0e501dd4ac0462e7a781f90fc1fb8f5cae0f9a9). Or do you mean the assets repo?

**Comment by kevmodrome** [comment]
Ah, you're right. Missed it there at the top 😨

**Review by kevmodrome — APPROVED** [review]
LGTM

**Pull request merged**
