### PR TITLE
Improve components page

### PR DESCRIPTION
**Pull request by MacFJA**
- Fix the display of tags (allow wrapping)
- Transform fix components category to dynamic (based on the search result)
- Add tags filtering in the search result (UI to select tags is still missing)
- Categorizing components (not finish)

### CODE REVIEW

**Review by swyxio — APPROVED** [review]
love the work! ready to merge?

**Comment by MacFJA** [comment]
Yes It can be merged, if the current state of `src/pages/components/components.json` (categorizations not finished, and a bit opinionated) is not an issue, neither the fact that tags selection is not done yet (I'm working on it).

**Comment by MacFJA** [comment]
@kevmodrome There aren't any design for the filter menu, I made this, is it ok?

When hovering the filter button:
Tags filter - list

---

When at least one tag is selected (Arrow is blue)
tags-filter-active

**Comment by swyxio** [comment]
i mean it looks good to me :) definitely super appreciate that you picked up on this when neither of us have made the time yet

**Pull request merged**
