### PR TITLE
feat: Create Components Page

### PR DESCRIPTION
**Pull request by cstrnt**

### CODE REVIEW

**Comment by stephane-vanraes** [comment]
I tried merging your changes locally, but it seems a fair amount of things have changed between master and staging. Could you apply your changes to *your* staging branch first and integrate them into the rest of the staging branch ?

You can normally afterwards change the PR to be from your staging branch, no need to open another request 🙂 

I hacked a bit around to get your new page working and it looks really great 👍 👍 💯

**Comment by kevmodrome** [comment]
@cstrnt pinging you again to see if this is something you have time for, if not I will take a look at some point :)

**Comment by cstrnt** [comment]
Hey guys, sorry for inactivity :( I just merged the staging branch into my master branch. I hope everything is alright now

**Review by kevmodrome — APPROVED** [review]

**Comment by kevmodrome** [comment]
Thanks a bunch for this! Much appreciated! 👍 I'll get you a shoutout on Twitter in a bit! 🙏

**Pull request merged**
