### PR TITLE
Resolves #81

### LINKED ISSUE #81: Move components over from Community to this repo
We need to move over the components from the old Community site to this one. They can be found here: https://github.com/sveltejs/community/blob/master/data/code.yml

Should be put in a data folder in the root.

Requirments: 
- It should be stored in a JSON format
- Make sure the data lines up with what is in the figma design: https://www.figma.com/file/CWyNLNaQI4yfHULrf1i4UC/Svelte-Society-Website?node-id=172%3A0

### PR DESCRIPTION
**Pull request by zygen**
Move components from the old repo to this one, transforming from yaml to json, and dropping unneccessary fields.

For reference, here are the commands I used
```
ruby -ryaml -rjson -e 'puts JSON.pretty_generate(YAML.load(ARGF))' < code.yml > code.json
jq '.resources | map(del(.stars, .last_updated, .downloads))' code.json > components.json
```

### CODE REVIEW

**Comment by swyxio** [comment]
nice thanks! do we need to wire this up in the code for it to show up?

also @kevmodrome how come netlify deploy previews dont show up here, is there an app we need to add to enable this?

**Comment by zygen** [comment]
Ah, I thought the issue was only for the data part, I see where it's supposed to go, so I'll go ahead and make the page as well.

**Comment by zygen** [comment]
Ok, so in attempting to wire up this data, I notice the design leans rather heavily on an image preview.  What should we do considering none of these components currently has one of those?  I see some further transformations that will be needed based on the ComponentCard: 
- rename `name` => `title`, 
- remove `last_updated`, 
- remove `downloads`, 
- add an `addedOn` field populated with todays date
- add an `active` field that defaults to true(?)
- add a `category` and someone will have to manually categorize each component

**Comment by swyxio** [comment]
lets drop all images for this PR, and do those transformations in one clear step!

**Comment by kevmodrome** [comment]
Sorry, missed this one (I really need to fix GitHub notifications). This site is hosted on cloudflare workers, is it possible to set it up to use netlify to just preview?

**Review by kevmodrome — APPROVED** [review]

**Comment by swyxio** [comment]
@kevmodrome yes its possible

**Comment by kevmodrome** [comment]
All right, I think it's set up now. Hopefully. 👍

**Pull request merged**
