### PR TITLE
Recipe index page

### PR DESCRIPTION
**Pull request by ChaitanyaGadodia**
As per the designs mentioned in: https://github.com/svelte-society/sveltesociety.dev/issues/34

### CODE REVIEW

**Comment by ChaitanyaGadodia** [comment]
Not yet completed, still a draft.

**Comment by ChaitanyaGadodia** [comment]
Please review @kevmodrome @sw-yx

**Comment by swyxio** [comment]
i removed the justify text content, too ugly. added `<main>` so there is some margin on mobile.


here's what i have pushed 
localhost_5000_recipes (1)

**Review by kevmodrome — APPROVED** [review]

**Comment by kevmodrome** [comment]
Merging this and we can do adjustments later

**Pull request merged**
