### PR TITLE
add `<svelte:options immutable>` recipe

### LINKED ISSUE #66: Recipe request: Immutable flag and how it works
Having read a comment by @ryanatkn in #60 it's dawning on me that we should have a recipe on how the immutable flag works, what it does, any performance implications, etc.

### PR DESCRIPTION
**Pull request by swyxio**
closes https://github.com/svelte-society/sveltesociety.dev/issues/66 with an initial attempt - feel free to add or modify!

### CODE REVIEW

**Review by kevmodrome — APPROVED** [review]

**Comment by kevmodrome** [comment]
Nice work Shawn!

**Comment by swyxio** [comment]
hmm. is CD broken? 

i dont see it on recipes page 
image

**Comment by geoffrich** [comment]
@sw-yx the site uses a staging branch now, you can see it at https://staging.sveltesociety.dev/recipes/svelte-language-fundamentals/options-immutable

**Comment by frederikhors** [comment]
Link to https://svelte.dev/docs#svelte_options doesn't work (Chrome 88, Win 10).

UPDATE:

This is a docs website bug: https://github.com/sveltejs/svelte/issues/5410.

**Pull request merged**
