### PR TITLE
Tags

### PR DESCRIPTION
**Pull request by kamalkech**
Update tags for package svelte formly

### CODE REVIEW

**Comment by stephane-vanraes** [comment]
The tags `dynamic form` and `reactive form` do not exist.

**Comment by kamalkech** [comment]
@stephane-vanraes i remove unexesting tags

**Comment by stephane-vanraes** [comment]
please remove `reactive forms` as well :)

**Comment by kamalkech** [comment]
@stephane-vanraes 
reactive forms in white list of tags, so i guess it s ok if not can u plz give all list tags accepted ?!!
check this capture

Components-Svelte-Society

**Review by stephane-vanraes — APPROVED** [review]

**Pull request merged**
