### PR TITLE
Components page responsiveness

### PR DESCRIPTION
**Pull request by UnevenCoder**
In mobile version text size and stuff have to be checked kinda , all others done .. lemme know if any improvement is needed

### CODE REVIEW

**Comment by kevmodrome** [comment]
You can mention issues and PR's like so: `#26`. For example: #26. I'll review.

**Comment by UnevenCoder** [comment]
sorry didn't know ,will do in future :)

**Review by kevmodrome — CHANGES_REQUESTED** [review]
This is not enough to make it responsive. There's a max-width on the cards that needs to be removed, for example. Make sure the image looks good when the cards themselves are stretched. I suggest you use `object-fit` to achieve this. Oh, and the controls at the top need to be fixed as well.

**Comment by UnevenCoder** [comment]
oh will look into it today night and tomorrow 👍

**Comment by UnevenCoder** [comment]
how do you want the controls to be responsive ?

**Comment by kevmodrome** [comment]
The design should be in the Figma document linked in the issue. Posting some extra information in the issue.

**Comment by kevmodrome** [comment]
Closing this, since author hasn't made updates, please re-open if you want to try your hand at this again

**Comment by UnevenCoder** [comment]
Really sry I completely forgot about it + exams will reopen & work on it after 25th

**Pull request closed without merging**
